name: Continuous Integration

on:
  push:
    branches:
      - master
      - 'feature*'
      - 'hotfix*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pruebas de SAST
      run: echo "Ejecución de pruebas de SAST"

    - name: Crear archivo de credenciales
      run: |
        cp path/to/credentials.ini.tpl credentials.ini
        sed -i "s/\${USERNAME}/${USERNAME}/g" credentials.ini
        sed -i "s/\${PASSWORD}/${PASSWORD}/g" credentials.ini
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}

    - name: Build docker image
      run: |
        docker build -t devops_ws . --tag devops_ws_$(date +%s)